//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andreani.Staging.Service
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pieza", Namespace="http://www.andreani.com.ar/req")]
    public partial class Pieza : object
    {
        
        private string NroPiezaField;
        
        private string NroAndreaniField;
        
        private string CodigoClienteField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string NroPieza
        {
            get
            {
                return this.NroPiezaField;
            }
            set
            {
                this.NroPiezaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string NroAndreani
        {
            get
            {
                return this.NroAndreaniField;
            }
            set
            {
                this.NroAndreaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string CodigoCliente
        {
            get
            {
                return this.CodigoClienteField;
            }
            set
            {
                this.CodigoClienteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pieza", Namespace="http://www.andreani.com.ar/res")]
    public partial class Pieza1 : object
    {
        
        private string NroPiezaField;
        
        private System.Collections.Generic.List<Andreani.Staging.Service.Envio> EnviosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string NroPieza
        {
            get
            {
                return this.NroPiezaField;
            }
            set
            {
                this.NroPiezaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Collections.Generic.List<Andreani.Staging.Service.Envio> Envios
        {
            get
            {
                return this.EnviosField;
            }
            set
            {
                this.EnviosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Envio", Namespace="http://www.andreani.com.ar/res")]
    public partial class Envio : object
    {
        
        private string NombreEnvioField;
        
        private string NroAndreaniField;
        
        private System.DateTime FechaAltaField;
        
        private System.Collections.Generic.List<Andreani.Staging.Service.Evento> EventosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEnvio
        {
            get
            {
                return this.NombreEnvioField;
            }
            set
            {
                this.NombreEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroAndreani
        {
            get
            {
                return this.NroAndreaniField;
            }
            set
            {
                this.NroAndreaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime FechaAlta
        {
            get
            {
                return this.FechaAltaField;
            }
            set
            {
                this.FechaAltaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.List<Andreani.Staging.Service.Evento> Eventos
        {
            get
            {
                return this.EventosField;
            }
            set
            {
                this.EventosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evento", Namespace="http://www.andreani.com.ar/res")]
    public partial class Evento : object
    {
        
        private System.DateTime FechaField;
        
        private string EstadoField;
        
        private string MotivoField;
        
        private string SucursalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Motivo
        {
            get
            {
                return this.MotivoField;
            }
            set
            {
                this.MotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Sucursal
        {
            get
            {
                return this.SucursalField;
            }
            set
            {
                this.SucursalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PiezaConsultas", Namespace="http://www.andreani.com.ar/req")]
    public partial class PiezaConsultas : object
    {
        
        private string CodigoClienteField;
        
        private System.Collections.Generic.List<Andreani.Staging.Service.Pieza2> PiezasField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoCliente
        {
            get
            {
                return this.CodigoClienteField;
            }
            set
            {
                this.CodigoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<Andreani.Staging.Service.Pieza2> Piezas
        {
            get
            {
                return this.PiezasField;
            }
            set
            {
                this.PiezasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pieza", Namespace="http://schemas.datacontract.org/2004/07/EAndreaniWS")]
    public partial class Pieza2 : object
    {
        
        private string NroPiezaField;
        
        private string NroAndreaniField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string NroPieza
        {
            get
            {
                return this.NroPiezaField;
            }
            set
            {
                this.NroPiezaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string NroAndreani
        {
            get
            {
                return this.NroAndreaniField;
            }
            set
            {
                this.NroAndreaniField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://www.andreani.com.ar/res")]
    public partial class Respuesta : object
    {
        
        private System.Collections.Generic.List<Andreani.Staging.Service.PiezaExitosa> PiezaExitosaField;
        
        private System.Collections.Generic.List<Andreani.Staging.Service.Error> ErroresField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Andreani.Staging.Service.PiezaExitosa> PiezaExitosa
        {
            get
            {
                return this.PiezaExitosaField;
            }
            set
            {
                this.PiezaExitosaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Collections.Generic.List<Andreani.Staging.Service.Error> Errores
        {
            get
            {
                return this.ErroresField;
            }
            set
            {
                this.ErroresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PiezaExitosa", Namespace="http://schemas.datacontract.org/2004/07/EAndreaniWS")]
    public partial class PiezaExitosa : object
    {
        
        private string NroPiezaField;
        
        private string NroAndreaniField;
        
        private string EstadoField;
        
        private System.DateTime FechaField;
        
        private string MotivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string NroPieza
        {
            get
            {
                return this.NroPiezaField;
            }
            set
            {
                this.NroPiezaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string NroAndreani
        {
            get
            {
                return this.NroAndreaniField;
            }
            set
            {
                this.NroAndreaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Motivo
        {
            get
            {
                return this.MotivoField;
            }
            set
            {
                this.MotivoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/EAndreaniWS")]
    public partial class Error : object
    {
        
        private string NroPiezaField;
        
        private string NroAndreaniField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroPieza
        {
            get
            {
                return this.NroPiezaField;
            }
            set
            {
                this.NroPiezaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string NroAndreani
        {
            get
            {
                return this.NroAndreaniField;
            }
            set
            {
                this.NroAndreaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnviosConsultas", Namespace="http://www.andreani.com.ar/req")]
    public partial class EnviosConsultas : object
    {
        
        private string CodigoClienteField;
        
        private System.Collections.Generic.List<Andreani.Staging.Service.Envio1> EnviosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoCliente
        {
            get
            {
                return this.CodigoClienteField;
            }
            set
            {
                this.CodigoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<Andreani.Staging.Service.Envio1> Envios
        {
            get
            {
                return this.EnviosField;
            }
            set
            {
                this.EnviosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Envio", Namespace="http://schemas.datacontract.org/2004/07/EAndreaniWS")]
    public partial class Envio1 : object
    {
        
        private string IdentificadorClienteField;
        
        private string NumeroAndreaniField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string IdentificadorCliente
        {
            get
            {
                return this.IdentificadorClienteField;
            }
            set
            {
                this.IdentificadorClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string NumeroAndreani
        {
            get
            {
                return this.NumeroAndreaniField;
            }
            set
            {
                this.NumeroAndreaniField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnviosRespuesta", Namespace="http://www.andreani.com.ar/res")]
    public partial class EnviosRespuesta : object
    {
        
        private System.Collections.Generic.List<Andreani.Staging.Service.EnvioExitoso> EnviosExitososField;
        
        private System.Collections.Generic.List<Andreani.Staging.Service.ErrorEnvio> EnviosErroneosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Andreani.Staging.Service.EnvioExitoso> EnviosExitosos
        {
            get
            {
                return this.EnviosExitososField;
            }
            set
            {
                this.EnviosExitososField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Collections.Generic.List<Andreani.Staging.Service.ErrorEnvio> EnviosErroneos
        {
            get
            {
                return this.EnviosErroneosField;
            }
            set
            {
                this.EnviosErroneosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnvioExitoso", Namespace="http://www.andreani.com.ar/res")]
    public partial class EnvioExitoso : object
    {
        
        private string IdentificadorClienteField;
        
        private string NumeroAndreaniField;
        
        private int IdEstadoField;
        
        private string EstadoField;
        
        private System.DateTime FechaField;
        
        private int IdMotivoField;
        
        private string MotivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string IdentificadorCliente
        {
            get
            {
                return this.IdentificadorClienteField;
            }
            set
            {
                this.IdentificadorClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string NumeroAndreani
        {
            get
            {
                return this.NumeroAndreaniField;
            }
            set
            {
                this.NumeroAndreaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int IdEstado
        {
            get
            {
                return this.IdEstadoField;
            }
            set
            {
                this.IdEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int IdMotivo
        {
            get
            {
                return this.IdMotivoField;
            }
            set
            {
                this.IdMotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Motivo
        {
            get
            {
                return this.MotivoField;
            }
            set
            {
                this.MotivoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorEnvio", Namespace="http://www.andreani.com.ar/res")]
    public partial class ErrorEnvio : object
    {
        
        private string IdentificadorClienteField;
        
        private string NumeroAndreaniField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificadorCliente
        {
            get
            {
                return this.IdentificadorClienteField;
            }
            set
            {
                this.IdentificadorClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroAndreani
        {
            get
            {
                return this.NumeroAndreaniField;
            }
            set
            {
                this.NumeroAndreaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NroPieza", Namespace="http://www.andreani.com.ar/req")]
    public partial class NroPieza : object
    {
        
        private string NroPiezaMemberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="NroPieza", IsRequired=true, EmitDefaultValue=false)]
        public string NroPiezaMember
        {
            get
            {
                return this.NroPiezaMemberField;
            }
            set
            {
                this.NroPiezaMemberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaEnvio", Namespace="http://www.andreani.com.ar/res")]
    public partial class RespuestaEnvio : object
    {
        
        private string NumeroEnvioField;
        
        private System.Collections.Generic.List<Andreani.Staging.Service.Envio_> EnviosField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string NumeroEnvio
        {
            get
            {
                return this.NumeroEnvioField;
            }
            set
            {
                this.NumeroEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Collections.Generic.List<Andreani.Staging.Service.Envio_> Envios
        {
            get
            {
                return this.EnviosField;
            }
            set
            {
                this.EnviosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Envio_", Namespace="http://www.andreani.com.ar/res")]
    public partial class Envio_ : object
    {
        
        private string NombreEnvioField;
        
        private string NroAndreaniField;
        
        private System.DateTime FechaAltaField;
        
        private System.Collections.Generic.List<Andreani.Staging.Service.Evento_> EventosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEnvio
        {
            get
            {
                return this.NombreEnvioField;
            }
            set
            {
                this.NombreEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroAndreani
        {
            get
            {
                return this.NroAndreaniField;
            }
            set
            {
                this.NroAndreaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime FechaAlta
        {
            get
            {
                return this.FechaAltaField;
            }
            set
            {
                this.FechaAltaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Collections.Generic.List<Andreani.Staging.Service.Evento_> Eventos
        {
            get
            {
                return this.EventosField;
            }
            set
            {
                this.EventosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evento_", Namespace="http://www.andreani.com.ar/res")]
    public partial class Evento_ : object
    {
        
        private System.DateTime FechaField;
        
        private int IdEstadoField;
        
        private string EstadoField;
        
        private int IdMotivoField;
        
        private string MotivoField;
        
        private string SucursalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstado
        {
            get
            {
                return this.IdEstadoField;
            }
            set
            {
                this.IdEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int IdMotivo
        {
            get
            {
                return this.IdMotivoField;
            }
            set
            {
                this.IdMotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Motivo
        {
            get
            {
                return this.MotivoField;
            }
            set
            {
                this.MotivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Sucursal
        {
            get
            {
                return this.SucursalField;
            }
            set
            {
                this.SucursalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.andreani.com.ar", ConfigurationName="Andreani.Staging.Service.IService")]
    public interface IService
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.andreani.com.ar/IService/ObtenerTrazabilidad", ReplyAction="http://www.andreani.com.ar/IService/ObtenerTrazabilidadResponse")]
        System.Threading.Tasks.Task<Andreani.Staging.Service.ObtenerTrazabilidadResponse> ObtenerTrazabilidadAsync(Andreani.Staging.Service.ObtenerTrazabilidadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.andreani.com.ar/IService/ObtenerEstadoDistribucion", ReplyAction="http://www.andreani.com.ar/IService/ObtenerEstadoDistribucionResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Piezas")]
        System.Threading.Tasks.Task<Andreani.Staging.Service.Respuesta> ObtenerEstadoDistribucionAsync(Andreani.Staging.Service.PiezaConsultas Consulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.andreani.com.ar/IService/ObtenerEstadoDistribucionCodificado", ReplyAction="http://www.andreani.com.ar/IService/ObtenerEstadoDistribucionCodificadoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Respuestas")]
        System.Threading.Tasks.Task<Andreani.Staging.Service.EnviosRespuesta> ObtenerEstadoDistribucionCodificadoAsync(Andreani.Staging.Service.EnviosConsultas EnviosConsultas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.andreani.com.ar/IService/ObtenerTrazabilidadSinCliente", ReplyAction="http://www.andreani.com.ar/IService/ObtenerTrazabilidadSinClienteResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Pieza")]
        System.Threading.Tasks.Task<Andreani.Staging.Service.Pieza1> ObtenerTrazabilidadSinClienteAsync(Andreani.Staging.Service.NroPieza NroPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.andreani.com.ar/IService/ObtenerTrazabilidadCodificado", ReplyAction="http://www.andreani.com.ar/IService/ObtenerTrazabilidadCodificadoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Respuesta")]
        System.Threading.Tasks.Task<Andreani.Staging.Service.RespuestaEnvio> ObtenerTrazabilidadCodificadoAsync(Andreani.Staging.Service.Pieza NroPieza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.andreani.com.ar/IService/ObtenerTrazabilidadSinClienteCodificado", ReplyAction="http://www.andreani.com.ar/IService/ObtenerTrazabilidadSinClienteCodificadoRespon" +
            "se")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="RespuestaEnvio")]
        System.Threading.Tasks.Task<Andreani.Staging.Service.RespuestaEnvio> ObtenerTrazabilidadSinClienteCodificadoAsync(Andreani.Staging.Service.NroPieza NroPieza);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerTrazabilidad", WrapperNamespace="http://www.andreani.com.ar", IsWrapped=true)]
    public partial class ObtenerTrazabilidadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.andreani.com.ar", Order=0)]
        public Andreani.Staging.Service.Pieza Pieza;
        
        public ObtenerTrazabilidadRequest()
        {
        }
        
        public ObtenerTrazabilidadRequest(Andreani.Staging.Service.Pieza Pieza)
        {
            this.Pieza = Pieza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerTrazabilidadResponse", WrapperNamespace="http://www.andreani.com.ar", IsWrapped=true)]
    public partial class ObtenerTrazabilidadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.andreani.com.ar", Order=0)]
        public Andreani.Staging.Service.Pieza1 Pieza;
        
        public ObtenerTrazabilidadResponse()
        {
        }
        
        public ObtenerTrazabilidadResponse(Andreani.Staging.Service.Pieza1 Pieza)
        {
            this.Pieza = Pieza;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServiceChannel : Andreani.Staging.Service.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Andreani.Staging.Service.IService>, Andreani.Staging.Service.IService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServiceSoap12.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Andreani.Staging.Service.ObtenerTrazabilidadResponse> ObtenerTrazabilidadAsync(Andreani.Staging.Service.ObtenerTrazabilidadRequest request)
        {
            return base.Channel.ObtenerTrazabilidadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Andreani.Staging.Service.Respuesta> ObtenerEstadoDistribucionAsync(Andreani.Staging.Service.PiezaConsultas Consulta)
        {
            return base.Channel.ObtenerEstadoDistribucionAsync(Consulta);
        }
        
        public System.Threading.Tasks.Task<Andreani.Staging.Service.EnviosRespuesta> ObtenerEstadoDistribucionCodificadoAsync(Andreani.Staging.Service.EnviosConsultas EnviosConsultas)
        {
            return base.Channel.ObtenerEstadoDistribucionCodificadoAsync(EnviosConsultas);
        }
        
        public System.Threading.Tasks.Task<Andreani.Staging.Service.Pieza1> ObtenerTrazabilidadSinClienteAsync(Andreani.Staging.Service.NroPieza NroPieza)
        {
            return base.Channel.ObtenerTrazabilidadSinClienteAsync(NroPieza);
        }
        
        public System.Threading.Tasks.Task<Andreani.Staging.Service.RespuestaEnvio> ObtenerTrazabilidadCodificadoAsync(Andreani.Staging.Service.Pieza NroPieza)
        {
            return base.Channel.ObtenerTrazabilidadCodificadoAsync(NroPieza);
        }
        
        public System.Threading.Tasks.Task<Andreani.Staging.Service.RespuestaEnvio> ObtenerTrazabilidadSinClienteCodificadoAsync(Andreani.Staging.Service.NroPieza NroPieza)
        {
            return base.Channel.ObtenerTrazabilidadSinClienteCodificadoAsync(NroPieza);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.e-andreani.com/eAndreaniWSStaging/Service.svc/soap12");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.ServiceSoap12);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.ServiceSoap12);
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap12,
        }
    }
}
